image: docker:24.0

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_BUILDKIT: 1
  IMAGE_VERSION: ""

services:
  - docker:dind

before_script:
  - export IMAGE_VERSION=$(date +"%y%m.%j")
  - |
    docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  - docker buildx create --name multiarch-builder --use
  - docker buildx inspect --bootstrap

gitlab:
  stage: build
  script:
    - cd server
    - echo -n $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
    - docker buildx build --platform linux/amd64,linux/arm64 -t $CI_REGISTRY_IMAGE:latest --push .
    - docker logout
  only:
    - main

docker hub:
  stage: build
  script:
    - cd server
    - echo -n $DOCKERHUB_ACCESS_TOKEN | docker login -u madmachinations --password-stdin
    - docker buildx build --platform linux/amd64,linux/arm64 -t madmachinations/ha-alexa-shopping-list-sync:$IMAGE_VERSION -t madmachinations/ha-alexa-shopping-list-sync:latest --push .
    - docker logout
  only:
    - main